/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WomensStudyImport } from './routes/womens-study'
import { Route as SchoolImport } from './routes/school'
import { Route as PrayerChainImport } from './routes/prayer-chain'
import { Route as PrayerImport } from './routes/prayer'
import { Route as MensStudyImport } from './routes/mens-study'
import { Route as LoginImport } from './routes/login'
import { Route as IdentityYouthImport } from './routes/identity-youth'
import { Route as GivingImport } from './routes/giving'
import { Route as EventsImport } from './routes/events'
import { Route as ErrorPageImport } from './routes/error-page'
import { Route as EldersImport } from './routes/elders'
import { Route as CurrentStudiesImport } from './routes/current-studies'
import { Route as BeliefsImport } from './routes/beliefs'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WomensStudyRoute = WomensStudyImport.update({
  id: '/womens-study',
  path: '/womens-study',
  getParentRoute: () => rootRoute,
} as any)

const SchoolRoute = SchoolImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRoute,
} as any)

const PrayerChainRoute = PrayerChainImport.update({
  id: '/prayer-chain',
  path: '/prayer-chain',
  getParentRoute: () => rootRoute,
} as any)

const PrayerRoute = PrayerImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRoute,
} as any)

const MensStudyRoute = MensStudyImport.update({
  id: '/mens-study',
  path: '/mens-study',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IdentityYouthRoute = IdentityYouthImport.update({
  id: '/identity-youth',
  path: '/identity-youth',
  getParentRoute: () => rootRoute,
} as any)

const GivingRoute = GivingImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRoute,
} as any)

const EventsRoute = EventsImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRoute,
} as any)

const ErrorPageRoute = ErrorPageImport.update({
  id: '/error-page',
  path: '/error-page',
  getParentRoute: () => rootRoute,
} as any)

const EldersRoute = EldersImport.update({
  id: '/elders',
  path: '/elders',
  getParentRoute: () => rootRoute,
} as any)

const CurrentStudiesRoute = CurrentStudiesImport.update({
  id: '/current-studies',
  path: '/current-studies',
  getParentRoute: () => rootRoute,
} as any)

const BeliefsRoute = BeliefsImport.update({
  id: '/beliefs',
  path: '/beliefs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/beliefs': {
      id: '/beliefs'
      path: '/beliefs'
      fullPath: '/beliefs'
      preLoaderRoute: typeof BeliefsImport
      parentRoute: typeof rootRoute
    }
    '/current-studies': {
      id: '/current-studies'
      path: '/current-studies'
      fullPath: '/current-studies'
      preLoaderRoute: typeof CurrentStudiesImport
      parentRoute: typeof rootRoute
    }
    '/elders': {
      id: '/elders'
      path: '/elders'
      fullPath: '/elders'
      preLoaderRoute: typeof EldersImport
      parentRoute: typeof rootRoute
    }
    '/error-page': {
      id: '/error-page'
      path: '/error-page'
      fullPath: '/error-page'
      preLoaderRoute: typeof ErrorPageImport
      parentRoute: typeof rootRoute
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsImport
      parentRoute: typeof rootRoute
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingImport
      parentRoute: typeof rootRoute
    }
    '/identity-youth': {
      id: '/identity-youth'
      path: '/identity-youth'
      fullPath: '/identity-youth'
      preLoaderRoute: typeof IdentityYouthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/mens-study': {
      id: '/mens-study'
      path: '/mens-study'
      fullPath: '/mens-study'
      preLoaderRoute: typeof MensStudyImport
      parentRoute: typeof rootRoute
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerImport
      parentRoute: typeof rootRoute
    }
    '/prayer-chain': {
      id: '/prayer-chain'
      path: '/prayer-chain'
      fullPath: '/prayer-chain'
      preLoaderRoute: typeof PrayerChainImport
      parentRoute: typeof rootRoute
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolImport
      parentRoute: typeof rootRoute
    }
    '/womens-study': {
      id: '/womens-study'
      path: '/womens-study'
      fullPath: '/womens-study'
      preLoaderRoute: typeof WomensStudyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beliefs': typeof BeliefsRoute
  '/current-studies': typeof CurrentStudiesRoute
  '/elders': typeof EldersRoute
  '/error-page': typeof ErrorPageRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/identity-youth': typeof IdentityYouthRoute
  '/login': typeof LoginRoute
  '/mens-study': typeof MensStudyRoute
  '/prayer': typeof PrayerRoute
  '/prayer-chain': typeof PrayerChainRoute
  '/school': typeof SchoolRoute
  '/womens-study': typeof WomensStudyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beliefs': typeof BeliefsRoute
  '/current-studies': typeof CurrentStudiesRoute
  '/elders': typeof EldersRoute
  '/error-page': typeof ErrorPageRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/identity-youth': typeof IdentityYouthRoute
  '/login': typeof LoginRoute
  '/mens-study': typeof MensStudyRoute
  '/prayer': typeof PrayerRoute
  '/prayer-chain': typeof PrayerChainRoute
  '/school': typeof SchoolRoute
  '/womens-study': typeof WomensStudyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/beliefs': typeof BeliefsRoute
  '/current-studies': typeof CurrentStudiesRoute
  '/elders': typeof EldersRoute
  '/error-page': typeof ErrorPageRoute
  '/events': typeof EventsRoute
  '/giving': typeof GivingRoute
  '/identity-youth': typeof IdentityYouthRoute
  '/login': typeof LoginRoute
  '/mens-study': typeof MensStudyRoute
  '/prayer': typeof PrayerRoute
  '/prayer-chain': typeof PrayerChainRoute
  '/school': typeof SchoolRoute
  '/womens-study': typeof WomensStudyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beliefs'
    | '/current-studies'
    | '/elders'
    | '/error-page'
    | '/events'
    | '/giving'
    | '/identity-youth'
    | '/login'
    | '/mens-study'
    | '/prayer'
    | '/prayer-chain'
    | '/school'
    | '/womens-study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beliefs'
    | '/current-studies'
    | '/elders'
    | '/error-page'
    | '/events'
    | '/giving'
    | '/identity-youth'
    | '/login'
    | '/mens-study'
    | '/prayer'
    | '/prayer-chain'
    | '/school'
    | '/womens-study'
  id:
    | '__root__'
    | '/'
    | '/beliefs'
    | '/current-studies'
    | '/elders'
    | '/error-page'
    | '/events'
    | '/giving'
    | '/identity-youth'
    | '/login'
    | '/mens-study'
    | '/prayer'
    | '/prayer-chain'
    | '/school'
    | '/womens-study'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeliefsRoute: typeof BeliefsRoute
  CurrentStudiesRoute: typeof CurrentStudiesRoute
  EldersRoute: typeof EldersRoute
  ErrorPageRoute: typeof ErrorPageRoute
  EventsRoute: typeof EventsRoute
  GivingRoute: typeof GivingRoute
  IdentityYouthRoute: typeof IdentityYouthRoute
  LoginRoute: typeof LoginRoute
  MensStudyRoute: typeof MensStudyRoute
  PrayerRoute: typeof PrayerRoute
  PrayerChainRoute: typeof PrayerChainRoute
  SchoolRoute: typeof SchoolRoute
  WomensStudyRoute: typeof WomensStudyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeliefsRoute: BeliefsRoute,
  CurrentStudiesRoute: CurrentStudiesRoute,
  EldersRoute: EldersRoute,
  ErrorPageRoute: ErrorPageRoute,
  EventsRoute: EventsRoute,
  GivingRoute: GivingRoute,
  IdentityYouthRoute: IdentityYouthRoute,
  LoginRoute: LoginRoute,
  MensStudyRoute: MensStudyRoute,
  PrayerRoute: PrayerRoute,
  PrayerChainRoute: PrayerChainRoute,
  SchoolRoute: SchoolRoute,
  WomensStudyRoute: WomensStudyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/beliefs",
        "/current-studies",
        "/elders",
        "/error-page",
        "/events",
        "/giving",
        "/identity-youth",
        "/login",
        "/mens-study",
        "/prayer",
        "/prayer-chain",
        "/school",
        "/womens-study"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/beliefs": {
      "filePath": "beliefs.tsx"
    },
    "/current-studies": {
      "filePath": "current-studies.tsx"
    },
    "/elders": {
      "filePath": "elders.tsx"
    },
    "/error-page": {
      "filePath": "error-page.tsx"
    },
    "/events": {
      "filePath": "events.tsx"
    },
    "/giving": {
      "filePath": "giving.tsx"
    },
    "/identity-youth": {
      "filePath": "identity-youth.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/mens-study": {
      "filePath": "mens-study.tsx"
    },
    "/prayer": {
      "filePath": "prayer.tsx"
    },
    "/prayer-chain": {
      "filePath": "prayer-chain.tsx"
    },
    "/school": {
      "filePath": "school.tsx"
    },
    "/womens-study": {
      "filePath": "womens-study.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
